Some clean-up on scripts that use alchemical and dual-topology options

diff --git a/bin/ffx b/bin/ffx
--- a/bin/ffx
+++ b/bin/ffx
@@ -137,13 +137,13 @@ if [ -x "$awkCmd" ]; then
     fi
 fi
 
-# Detect JDK version; disallow JDKs other than 21 up to 24.
+# Detect JDK version; disallow JDKs other than 21 up to 25.
 if [ $hasAwkSed ]; then
     JVERS="$(java -version 2>&1 | awk '/version/ {print $3;}' | sed 's/\"//g')"
     JVFIRST="$(echo "$JVERS" | awk 'BEGIN { FS = "[.-]"; } { print $1 }')"
 
-    if [ "$JVFIRST" -lt 21 ] || [ "$JVFIRST" -gt 24 ]; then
-        echo " Illegal Java version detected (${JVERS}). Please use JDK 21 through 24." 1>&2
+    if [ "$JVFIRST" -lt 21 ] || [ "$JVFIRST" -gt 25 ]; then
+        echo " Illegal Java version detected (${JVERS}). Please use JDK 21 through 25." 1>&2
         exit 1
     fi
 
@@ -169,7 +169,7 @@ if [ $hasAwkSed ]; then
       fi
     fi
 else
-    echo " The JRE and CUDA toolkit versions could not be autodetected. Please use JDK 21 through 24 and (optionally) CUDA toolkit 11.1 or later."
+    echo " The JRE and CUDA toolkit versions could not be autodetected. Please use JDK 21 through 25 and (optionally) CUDA toolkit 11.1 or later."
 fi
 
 # For Cygwin, switch paths to Windows format before running java
