Update FFX to depend on JDK 21

diff --git a/bin/ffx b/bin/ffx
--- a/bin/ffx
+++ b/bin/ffx
@@ -141,13 +141,13 @@ if [ -x "$awkCmd" ]; then
     fi
 fi
 
-# Detect JDK version; disallow JDKs below 17 and above 21.
+# Detect JDK version; disallow JDKs below 21 and above 21.1.
 if [ $hasAwkSed ]; then
     JVERS="`java -version 2>&1 | awk '/version/ {print $3;}' | sed 's/\"//g'`"
     JVFIRST="`echo "$JVERS" | awk 'BEGIN { FS = "[.-]"; } { print $1 }'`"
 
-    if [ $JVFIRST -lt 17 -o $JVFIRST -gt 21 ]; then
-        echo " Illegal Java version detected (${JVERS}). Please use JDK 17 through JDK 21." 1>&2
+    if [ $JVFIRST -lt 21 -o $JVFIRST -gt 21 ]; then
+        echo " Illegal Java version detected (${JVERS}). Please use JDK 21." 1>&2
     fi 
     
     EXTRA_JVM_ARGUMENTS="${EXTRA_JVM_ARGUMENTS} --add-opens=java.desktop/java.awt=ALL-UNNAMED --add-exports=java.base/java.lang=ALL-UNNAMED --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.desktop/sun.java2d=ALL-UNNAMED"
@@ -169,7 +169,7 @@ if [ $hasAwkSed ]; then
       fi
     fi
 else
-    echo " The JRE and CUDA toolkit versions could not be autodetected. Please use JDK 17 through JDK 21 and (optionally) CUDA toolkit 10.1 or later."
+    echo " The JRE and CUDA toolkit versions could not be autodetected. Please use JDK 21 and (optionally) CUDA toolkit 10.1 or later."
 fi
 
 # For Cygwin, switch paths to Windows format before running java
