Update to the released version Groovy v. 3.0.0; FFX now support JDK versions 1.8 up to 14

diff --git a/bin/ffx b/bin/ffx
--- a/bin/ffx
+++ b/bin/ffx
@@ -140,15 +140,15 @@ if [ -x "$awkCmd" ]; then
     fi
 fi
 
-# Detect JDK version; disallow JDKs below 1.8 and above 13.
+# Detect JDK version; disallow JDKs below 1.8 and above 14.
 if [ $hasAwkSed ]; then
     JVERS="`java -version 2>&1 | awk '/version/ {print $3;}' | sed 's/\"//g'`"
     JVFIRST="`echo "$JVERS" | awk 'BEGIN { FS = "[.-]"; } { print $1 }'`"
     JVSEC="`echo "$JVERS" | awk 'BEGIN { FS = "."; } { print $2 }'`"
 
     USE_EXPTL_FLAGS=''
-    if [ $JVFIRST -gt 13 ]; then
-        echo " Illegal Java version detected (${JVERS}). Please use JDK 1.8 through JDK 13." 1>&2
+    if [ $JVFIRST -gt 14 ]; then
+        echo " Illegal Java version detected (${JVERS}). Please use JDK 1.8 through JDK 14." 1>&2
 #       exit 1
     elif [ $JVFIRST -eq 9 ]; then
         USE_EXPTL_FLAGS='1'
@@ -160,8 +160,10 @@ if [ $hasAwkSed ]; then
         USE_EXPTL_FLAGS='1'
     elif [ $JVFIRST -eq 13 ]; then
         USE_EXPTL_FLAGS='1'
+    elif [ $JVFIRST -eq 14 ]; then
+        USE_EXPTL_FLAGS='1'
     elif [ $JVSEC -lt 8 ]; then
-        echo " Illegal Java version detected (${JVERS}). Please use JDK 1.8 through JDK 13." 1>&2
+        echo " Illegal Java version detected (${JVERS}). Please use JDK 1.8 through JDK 14." 1>&2
         exit 1
     fi
 
@@ -172,7 +174,7 @@ if [ $hasAwkSed ]; then
     nvccComm='which nvcc'
     hasNVCC=''
     if [ -x "$nvccComm" ]; then
-        hasNVCC='1'
+      hasNVCC='1'
     fi
     if [ $hasNVCC ]; then
       CVERS="`nvcc --version`"
@@ -190,7 +192,7 @@ if [ $hasAwkSed ]; then
       fi
     fi
 else
-    echo " The JRE and CUDA toolkit versions could not be autodetected. Please use JDK 1.8 through JDK 13 and (optionally) CUDA toolkit 10.1."
+    echo " The JRE and CUDA toolkit versions could not be autodetected. Please use JDK 1.8 through JDK 14 and (optionally) CUDA toolkit 10.1."
 fi
 
 # For Cygwin, switch paths to Windows format before running java
@@ -207,7 +209,7 @@ fi
 EXTRA_JVM_ARGUMENTS="${EXTRA_JVM_ARGUMENTS}"
 
 if $darwin; then
- exec "$JAVACMD" $JAVA_OPTS \
+  exec "$JAVACMD" $JAVA_OPTS \
   $EXTRA_JVM_ARGUMENTS \
   -classpath "$CLASSPATH" \
   -splash:"$BASEDIR/bin/splash.png" \
@@ -220,7 +222,7 @@ if $darwin; then
   ffx.Main \
   "$@"
 else
- exec "$JAVACMD" $JAVA_OPTS \
+  exec "$JAVACMD" $JAVA_OPTS \
   $EXTRA_JVM_ARGUMENTS \
   -classpath "$CLASSPATH" \
   -splash:"$BASEDIR/bin/splash.png" \
