Update to JavaDoc Plugin v. 3.1.0; Support the released version of JDK 12

diff --git a/bin/ffx b/bin/ffx
--- a/bin/ffx
+++ b/bin/ffx
@@ -138,8 +138,8 @@ if [ $hasAwkSed ]; then
     JVSEC="`echo "$JVERS" | awk 'BEGIN { FS = "."; } { print $2 }'`"
 
     USE_EXPTL_FLAGS=''
-    if [ $JVFIRST -gt 11 ]; then
-        echo " Illegal Java version detected (${JVERS}). Please use JDK 1.8, JDK 9, JDK 10 or JDK 11." 1>&2
+    if [ $JVFIRST -gt 12 ]; then
+        echo " Illegal Java version detected (${JVERS}). Please use JDK 1.8, JDK 9, JDK 10, JDK 11 or JDK 12." 1>&2
 #       exit 1
     elif [ $JVFIRST -eq 9 ]; then
         USE_EXPTL_FLAGS='1'
@@ -147,8 +147,10 @@ if [ $hasAwkSed ]; then
         USE_EXPTL_FLAGS='1'
     elif [ $JVFIRST -eq 11 ]; then
         USE_EXPTL_FLAGS='1'
+    elif [ $JVFIRST -eq 12 ]; then
+        USE_EXPTL_FLAGS='1'
     elif [ $JVSEC -lt 8 ]; then
-        echo " Illegal Java version detected (${JVERS}). Please use JDK 1.8, JDK 9, JDK 10 or JDK 11." 1>&2
+        echo " Illegal Java version detected (${JVERS}). Please use JDK 1.8, JDK 9, JDK 10, JDK 11 or JDK 12." 1>&2
         exit 1
     fi
 
@@ -156,8 +158,9 @@ if [ $hasAwkSed ]; then
         EXTRA_JVM_ARGUMENTS="${EXTRA_JVM_ARGUMENTS} --illegal-access=permit --add-opens=java.desktop/java.awt=ALL-UNNAMED --add-exports=java.base/java.lang=ALL-UNNAMED --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.desktop/sun.java2d=ALL-UNNAMED"
     fi
 else
-    echo " The JRE version could not be autodetected. Please use JDK 1.8, JDK 9, JDK 10 or JDK 11."
+    echo " The JRE version could not be autodetected. Please use JDK 1.8, JDK 9, JDK 10, JDK 11 or JDK 12."
 fi
+
 
 
 # For Cygwin, switch paths to Windows format before running java
