update FFX start-up detection of JRE version

diff --git a/bin/ffxc b/bin/ffxc
--- a/bin/ffxc
+++ b/bin/ffxc
@@ -117,24 +117,23 @@ if [ $hasAwkSed ]; then
     JVSEC="`echo "$JVERS" | awk 'BEGIN { FS = "."; } { print $2 }'`"
 
     USE_EXPTL_FLAGS=''
-    if [ $JVFIRST -gt 1 ]; then
-        #USE_EXPTL_FLAGS='1'
-        echo " FFX currently not supported by Java 10+. Preferably use JDK 1.8, found ${JVERS}" 1>&2
+    if [ $JVFIRST -gt 9 ]; then
+        echo " FFX currently does not supported by Java 10+ (JDK 1.8 is preferred) - detected ${JVERS}" 1>&2
         exit 1
-    elif [ $JVSEC -lt 8 ]; then
-        echo " Illegal Java version detected. Must use JDK 1.8 or above (preferably 1.8), found ${JVERS}" 1>&2
-        exit 1
-    elif [ $JVSEC -gt 8 ]; then
+    elif [ $JVFIRST -eq 9 ]; then
         USE_EXPTL_FLAGS='1'
+    elif [ $JVSEC -lt 8 ]; then
+        echo " Illegal Java version detected. Must use JDK 1.8 or JDK 9, found ${JVERS}" 1>&2
+        exit 1
     fi
 
     if [ $USE_EXPTL_FLAGS ]; then
-        echo " WARNING: JDK 9+ detected. JDK 1.8 very strongly recommended to prevent issues with updates to the JVM. FFX not guaranteed to run properly" 1>&2
+        echo " WARNING: JDK 9+ is detected and support is experimental." 1>&2
         echo '' 1>&2
         EXTRA_JVM_ARGUMENTS="${EXTRA_JVM_ARGUMENTS} --illegal-access=permit --add-opens=java.desktop/java.awt=ALL-UNNAMED --add-exports=java.base/java.lang=ALL-UNNAMED --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.desktop/sun.java2d=ALL-UNNAMED"
     fi
 else
-    echo " Cannot autodetect JVM version. JDK 1.8 preferred, else JDK 9 possibly compatible. Incompatible with any other JDK."
+    echo " The JRE version could not be autodetected. JRE 1.8 is preferred, and JRE 9 is experimental."
 fi
 
 # For Cygwin, switch paths to Windows format before running java
