Major update to FFX uses of Groovy to accomodate JDKs 8, 9 and 10. We now depend on the 2.5.0 release version of Groovy, and the PicoCLI version of CLIBuilder

diff --git a/bin/ffxc b/bin/ffxc
--- a/bin/ffxc
+++ b/bin/ffxc
@@ -113,29 +113,27 @@ fi
 # Detect JVM version; disallow 1.7 or below, warn for JDK 9+ that experimental flags are in use.
 if [ $hasAwkSed ]; then
     JVERS="`java -version 2>&1 | awk '/version/ {print $3;}' | sed 's/\"//g'`"
-    JVFIRST="`echo "$JVERS" | awk 'BEGIN { FS = "."; } { print $1 }'`"
+    JVFIRST="`echo "$JVERS" | awk 'BEGIN { FS = "[.-]"; } { print $1 }'`"
     JVSEC="`echo "$JVERS" | awk 'BEGIN { FS = "."; } { print $2 }'`"
 
     USE_EXPTL_FLAGS=''
-    if [ $JVFIRST -gt 9 ]; then
-        echo " FFX does not currently support Java 10+ (JDK 1.8 is preferred) - detected ${JVERS}" 1>&2
-        exit 1
+    if [ $JVFIRST -gt 10 ]; then
+        echo " Illegal Java version detected (${JVERS}). Please use JRE 1.8, JDK 9 or JDK 10." 1>&2
+#       exit 1
     elif [ $JVFIRST -eq 9 ]; then
         USE_EXPTL_FLAGS='1'
-    elif [ $JVSEC -eq 9 ]; then
+    elif [ $JVFIRST -eq 10 ]; then
         USE_EXPTL_FLAGS='1'
     elif [ $JVSEC -lt 8 ]; then
-        echo " Illegal Java version detected. Must use JDK 1.8 or JDK 9, found ${JVERS}" 1>&2
+        echo " Illegal Java version detected (${JVERS}). Please use JRE 1.8, JDK 9 or JDK 10." 1>&2
         exit 1
     fi
 
     if [ $USE_EXPTL_FLAGS ]; then
-        echo " WARNING: JDK 9 detected: support is experimental." 1>&2
-        echo '' 1>&2
         EXTRA_JVM_ARGUMENTS="${EXTRA_JVM_ARGUMENTS} --illegal-access=permit --add-opens=java.desktop/java.awt=ALL-UNNAMED --add-exports=java.base/java.lang=ALL-UNNAMED --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.desktop/sun.java2d=ALL-UNNAMED"
     fi
 else
-    echo " The JRE version could not be autodetected. JRE 1.8 is preferred, and JRE 9 is experimental."
+    echo " The JRE version could not be autodetected. Please use JRE 1.8, JDK 9 or JDK 10."
 fi
 
 # For Cygwin, switch paths to Windows format before running java
