Merge changes from the mjschnie/FFX fork

diff --git a/bin/ffxc b/bin/ffxc
--- a/bin/ffxc
+++ b/bin/ffxc
@@ -135,15 +135,15 @@ if [ -x "$awkCmd" ]; then
     fi
 fi
 
-# Detect JDK version; disallow JDKs below 1.8 and 11.
+# Detect JDK version; disallow JDKs below 1.8 and above 13.
 if [ $hasAwkSed ]; then
     JVERS="`java -version 2>&1 | awk '/version/ {print $3;}' | sed 's/\"//g'`"
     JVFIRST="`echo "$JVERS" | awk 'BEGIN { FS = "[.-]"; } { print $1 }'`"
     JVSEC="`echo "$JVERS" | awk 'BEGIN { FS = "."; } { print $2 }'`"
 
     USE_EXPTL_FLAGS=''
-    if [ $JVFIRST -gt 12 ]; then
-        echo " Illegal Java version detected (${JVERS}). Please use JDK 1.8, JDK 9, JDK 10, JDK 11 or JDK 12." 1>&2
+    if [ $JVFIRST -gt 13 ]; then
+        echo " Illegal Java version detected (${JVERS}). Please use JDK 1.8 through JDK 13." 1>&2
 #       exit 1
     elif [ $JVFIRST -eq 9 ]; then
         USE_EXPTL_FLAGS='1'
@@ -153,8 +153,10 @@ if [ $hasAwkSed ]; then
         USE_EXPTL_FLAGS='1'
     elif [ $JVFIRST -eq 12 ]; then
         USE_EXPTL_FLAGS='1'
+    elif [ $JVFIRST -eq 13 ]; then
+        USE_EXPTL_FLAGS='1'
     elif [ $JVSEC -lt 8 ]; then
-        echo " Illegal Java version detected (${JVERS}). Please use JDK 1.8, JDK 9, JDK 10, JDK 11 or JDK 12." 1>&2
+        echo " Illegal Java version detected (${JVERS}). Please use JDK 1.8 through JDK 13." 1>&2
         exit 1
     fi
 
@@ -162,7 +164,7 @@ if [ $hasAwkSed ]; then
         EXTRA_JVM_ARGUMENTS="${EXTRA_JVM_ARGUMENTS} --illegal-access=permit --add-opens=java.desktop/java.awt=ALL-UNNAMED --add-exports=java.base/java.lang=ALL-UNNAMED --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.desktop/sun.java2d=ALL-UNNAMED"
     fi
 else
-    echo " The JRE version could not be autodetected. Please use JDK 1.8, JDK 9, JDK 10, JDK 11 or JDK 12."
+    echo " The JRE version could not be autodetected. Please use JDK 1.8 through JDK 13."
 fi
 
 # For Cygwin, switch paths to Windows format before running java
